# Generated by Django 5.2 on 2025-04-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='Название')),
                ('url', models.CharField(max_length=240, verbose_name='URL страницы товара')),
                ('xpath', models.CharField(max_length=240, verbose_name='Путь к элементу с ценой')),
            ],
            options={
                'verbose_name': 'Правило парсинга товара',
                'verbose_name_plural': 'Правила парсинга товара',
            },
        ),
    ]
